name: build-master

on:
  push:
    branches:
      - master

jobs:
  build:
    if: "!contains(github.event.commits[0].message, 'Release')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: setup-node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - id: build-and-analyse
        run: |
          npm ci
          npm test
          npm run build